Fix compilation error: use ArgumentError instead of NotImplementedError
NotImplementedError class doesn't exist in the compiler environment.
Changed to ArgumentError which is more appropriate for unsupported
pow() modulo parameter anyway.

This fixes the build break introduced in previous commit.